### ISSUE TITLE
【Bug】Windows平台下下载完毕后不转入已完成界面

### ISSUE THREAD

**Issue by TartaricAcid** [imfanhua/iCraftDownloader#1]
**使用系统：**`Windows 7 `

**使用 iCraftDownloader 版本：**`Beta 1.0.2`

**问题描述：**
拖入curseforge整合包地址后，下载正常。但是下载全部完毕后，并不转入已完成界面，仍旧保留在进行中界面。但此时已经没有任何下载提示了。
具体可以参考如下图片，下载全部完毕后停留在此界面不动。

![pic](https://public.lightpic.info/image/8380_5A3C851E0.jpg)

**Comment by imfanhua** [comment]
可能是某些MOD解析失败，可重开程序后尝试再次拖入 （当前版本解析失败还没有提示）

**Comment by TartaricAcid** [comment]
重复试过两三次，还是无效，可能是某些mod地址已经无效了？

**Comment by imfanhua** [comment]
有可能，可否发一下整合包地址

**Comment by TartaricAcid** [comment]
https://minecraft.curseforge.com/projects/chiselsandbits-reddit

**Comment by imfanhua** [comment]
项目ID：238222，文件ID：2338920
的文件无法找到，大概是被作者自己删了？
https://minecraft.curseforge.com/projects/jei/files/2338920

**Comment by TartaricAcid** [comment]
看来应该做一个自动检测失效文件，并提示的功能

**Comment by imfanhua** [comment]
在计划之中，就跟代理功能一样 😄

**Comment by imfanhua** [comment]
问题解决了就先关闭了

**Comment by TartaricAcid** [comment]
辛苦你了_(:з」∠)_
