### ISSUE TITLE
关于下个版本

### ISSUE THREAD

**Issue by imfanhua** [imfanhua/iCraftDownloader#10]
由于我将全部代码重构了一遍（基本上就是全部删了重写 ;D，所以也请各位大佬先不要提交 Pull request）所以下个版本发布时间会大幅延后（虽然貌似也没有说过下个版本多久更新）故发布一下进度以及下个版本**可能**（*斜体*表示**不一定**会添加）会更新的新功能（特性）

---

- [x] 前后端分离
- [x] 前后端代码打包压缩 （解决 node_modules 黑洞问题）
- [x] ~~更多的Bug~~

---

- [x] [系统] 多语言
- [x] [系统] 多来源
- [x] [系统] 多格式
- [x] [系统] 多整合包格式
- [x] [系统] 任务
- [x] [系统] 缓存
- [x] [系统] 代理
- [x] [系统] 设置

---

- [x] [多语言] 简体中文
- [ ] [多语言] *English*

---

- [ ] [多来源] Curse 来源
- [ ] [多来源] 自定义格式 来源
- [ ] [多来源] 预置 自定义格式 来源 （会预置几个简单的来源，例如：MCBBS、B站视频、优酷视频）

---

- [ ] [多格式] 整合包
- [ ] [多格式] 模组

---

- [ ] [多整合包格式] MultiMC
- [ ] [多整合包格式] *HMCL*
- [ ] [多整合包格式] *BakaXL*

---

- [x] [任务] 取消功能
- [x] [任务] 重试功能
- [ ] [任务] 替换功能
- [ ] [任务] 忽略功能

---

- [x] [缓存] 清空功能

---

- [x] [代理] Socks5

---

- [x] [设置] 代理相关
- [ ] [设置] 下载相关
- [ ] [设置] 任务选择相关
- [ ] [设置] 下载完成相关

---

- [ ] [前端] UI （在做了，你繁哥哥骗过你吗？）

---

...等（可能有一些没有提到），欢迎各位在下面讨论

**Comment by imfanhua** [comment]
突然摸了几天.jpg

**Comment by 3TUSK** [comment]
说起多来源，我推荐看一下这个，对解决作者自行存档的 Mod **可能**有帮助：https://cursemeta.dries007.net

**Comment by imfanhua** [comment]
@3TUSK 感谢！会看的

**Comment by subtank** [comment]
求把api文件都统一打包到一个文件夹内啊。一拉全是API文件虽然很爽但是不利于管理。

**Comment by imfanhua** [comment]
@subtank 新版本是完全重写了整个项目，并且抽象化了很多部分，新版本代码质量肯定比现在这个好得多，不过新版本进度比较缓慢因为很多原因…… 😢

**Comment by ZeroAurora** [comment]
请问大佬，前后端分离是不同语言的吗
（也在写一个类似的 躺 恐怕完成不了）

**Comment by imfanhua** [comment]
@ZeroAurora 是同语言(TypeScript)，分成了三个模块 common (通用部分)、main (后端)、view (前端)，后端负责文件下载与整合包处理之类的事务，前端只负责接受后端传来的数据然后显示并且只回传用户操作实际如何处理是全权由后端负责的，common部分大多都是传递数据的结构 (当然有少数工具的实现)

**Comment by imfanhua** [comment]
@ZeroAurora 不同语言使用 Gradle 应该能满足你的需求 😄

**Comment by ZeroAurora** [comment]
@imfanhua 好的，谢繁大佬

**Comment by imfanhua** [comment]
@RelaperCrystal 一直都是JS的呀，不过这个最近我都没有在继续写了 （因为其他事情太多了 （简单来说就是：摸了））

**Comment by ZeroAurora** [comment]
妈耶这玩意是咕咕咕咕咕咕咕咕咕了吗（

**Comment by imfanhua** [comment]
@ZeroAurora 在做了，你繁鸽鸽骗过你吗（

**Comment by reserveword** [comment]
所以。。还在做吗

**Comment by imfanhua** [comment]
项目已停止维护
