### ISSUE TITLE
为什么不能使用IE代理?

### ISSUE THREAD

**Issue by Huyil** [imfanhua/iCraftDownloader#11]
没有经过本地IP:127.0.0.1
无法使用加速器加速emmmmmm

―――――――――――――――――――――――
程序名称：iCraftDownloader.exe
程序说明：iCraftDownloader
路径：C:\Users\MacBook\Desktop\iCraftDownloader\iCraftDownloader.exe
安全等级：未知
PID：3504
网络协议：TCP
本机地址：192.168.1.100
本地端口：54571
目标地址：52.85.153.243
目标端口：443
目标IP归属地：美国  特拉华州dupont公司
状态：连接

网络连接信息由360安全卫士 – 网络连接查看器生成
―――――――――――――――――――――――

**Comment by imfanhua** [comment]
这个版本还不能使用代理，下个版本会添加socks5代理的支持，但是HTTP代理支持不支持还是未知数，下个版本可以看 #10 这里 😄
