### ISSUE TITLE
有的整合包下载到最后两个MOD下不动了

### ISSUE THREAD

**Issue by as495969** [imfanhua/iCraftDownloader#12]
modern skyblock 3:departed 的better questing(3.5.253)和immersive clbles(1.3.0)
ftb presents skyfactory 3的packing tape(0.6.0)和solar flux reborn(2.17r)

**Comment by imfanhua** [comment]
iCraftDownloader 已经很久没有更新了，目前也暂时没有更新的打算，不过 iCraftDownloader-Windows (Windows 平台限定版) 在开发中，请发布后尝试这个版本，目前的解决方案是使用 https://github.com/Vazkii/CMPDL 暂时代替

**Comment by imfanhua** [comment]
项目已停止维护
