### ISSUE TITLE
Linux中无法启动可执行文件

### ISSUE THREAD

**Issue by EvanMeek** [imfanhua/iCraftDownloader#13]
内核是Deepin，在iCarftDownloader文件夹內终端命令［./iCraftDownloader］提示找不到命令，或者说是我启动方式有问题么？

![image](https://user-images.githubusercontent.com/27056033/42849513-17495232-8a56-11e8-9ddb-31a1bbd863cb.png)

**Comment by imfanhua** [comment]
以及 #12

**Comment by imfanhua** [comment]
项目已停止维护
