### ISSUE TITLE
【Bug】linux x64 程序无法启动

### ISSUE THREAD

**Issue by TartaricAcid** [imfanhua/iCraftDownloader#2]
使用系统：`Ubuntu 16.04`

使用 iCraftDownloader 版本：Beta 1.0.2

问题描述：
下载文件为`iCraftDownloader-beta-1.0.2-linux-x64.zip`，解压后运行`iCraftDownloader`文件，选择用`运行软件`选项运行，无反应。
![pic](https://public.lightpic.info/image/E136_5A3C8AAF0.jpg)

**Comment by imfanhua** [comment]
大概率是打包平台问题？打包源是官方的

**Comment by HigZxcvd** [comment]
文件权限问题 在目录中右键-在终端打开 运行"chmod +x ./iCraftDownloader"即可解决

**Comment by TartaricAcid** [comment]
@HigZxcvd 感谢，果然是权限问题，现在已经解决
