### ISSUE TITLE
检测不到

### ISSUE THREAD

**Issue by 462820950** [imfanhua/iCraftDownloader#3]
为什么下载完无法检测到？

**Comment by imfanhua** [comment]
请提交一下拖拽的地址以及程序最后呈现出什么状态，最好能附图

**Comment by 462820950** [comment]
![icraftdownloader 2017_12_23 23_03_59](https://user-images.githubusercontent.com/32917125/34320451-a2bbadba-e835-11e7-8819-ee7720fda792.png)

**Comment by 462820950** [comment]
天空农场3

**Comment by imfanhua** [comment]
看图可能是某些MOD下载失败，重开程序重新拖拽一次试试应该能解决

**Comment by 462820950** [comment]
试了好多次，还是下不了

**Comment by imfanhua** [comment]
能发一下拖拽的地址吗

**Comment by imfanhua** [comment]
没有拖拽的地址的话只能猜测为：
1.整合包中某个指定的MOD文件不存在无法下载
2.整合包中某个指定的MOD文件下载失败
3.全部MOD都已成功下载程序处于生成整合包阶段

**Comment by 462820950** [comment]
不是拖拽的，是添加的

**Comment by imfanhua** [comment]
那请发一下添加的地址，谢谢了

**Comment by 462820950** [comment]
https://www.curseforge.com/minecraft/modpacks/ftb-presents-skyfactory-3

**Comment by 462820950** [comment]
![icraftdownloader 2017_12_23 23_03_59](https://user-images.githubusercontent.com/32917125/34324582-2545c32e-e8b3-11e7-821d-902924ffc2c6.png)
添加之后就是这样，MOD下完了，加载一下就这样了

**Comment by 997035270** [comment]
我的有个别mod下载不了 一直0%

**Comment by imfanhua** [comment]
问题与 https://github.com/imfanhua/iCraftDownloader/issues/1 一样
项目ID：32274，文件ID：2477511
的文件无法找到，大概是被作者自己删了？
https://minecraft.curseforge.com/projects/32274/files/2477511

**Comment by imfanhua** [comment]
下个版本会尝试添加一个忽略个别MOD的按钮 （大概，或者用别的方式来解决这种问题）

**Comment by 997035270** [comment]
繁华 问你件事你还记得逍遥吗

**Comment by imfanhua** [comment]
这里只用来处理 iCraftDownloader 的相关问题/意见/建议，闲聊可以通过微博私信 :D

**Comment by 462820950** [comment]
cmpdl可以下吗

**Comment by imfanhua** [comment]
没有尝试过，不知道CMPDL遇到这种情况会如何处理

**Comment by imfanhua** [comment]
@997035270 你的问题不属于这一条 Issue，如果下载卡住应该是网络问题，你可以尝试重开程序重新拖拽/添加再试

**Comment by 997035270** [comment]
尝试过了 但是还是这样 而且#3这个问题我也有

**Comment by imfanhua** [comment]
@997035270 那我开个新的 Issue 讨论一下如何处理这种情况吧

**Comment by 997035270** [comment]
嗯

**Comment by 3284530074** [comment]
iCraftDownloader显示指定目标无效或网络错误

**Comment by imfanhua** [comment]
@3284530074 这个项目已经不再维护了

**Comment by 3284530074** [comment]
那还有什么可以玩curse上的整合包

**Comment by imfanhua** [comment]
@3284530074 你可以试试 MultiMC (https://multimc.org/)

**Comment by 3284530074** [comment]
这个游戏启动不了显示退出代码：1

**Comment by imfanhua** [comment]
@3284530074 你可以去他们的discord上提一下这个问题，服务器上应该还是有许多国人的，具体问题还是需要log文件我这边已经无法帮到你了

**Comment by 3284530074** [comment]
嗯
