### ISSUE TITLE
Win64版本(1.0.2)无法正常运行

### ISSUE THREAD

**Issue by bxz2311196368** [imfanhua/iCraftDownloader#4]
程序打不开，使用管理员权限后才能打开，但是是一个空窗口
![default](https://user-images.githubusercontent.com/22958783/34323966-8266c23e-e899-11e7-9fcd-b28d1cb2b232.PNG)
（没找到日志在哪，只能上传个截图了）

**Comment by imfanhua** [comment]
这个问题就恨奇怪了，请问系统是否为精简版

**Comment by bxz2311196368** [comment]
系统是完整的，32位的能运行，但是下载卡在0%

**Comment by bxz2311196368** [comment]
刚刚又试了一下，32位的下载不到一半就没了，已完成和进行中都没有内容。
cache文件夹只有两个文件，temp文件夹下都是空文件夹，没有文件。尝试使用WinRAR打开264853-2511581这个文件“显示不可预料的压缩文件末端”。
![default](https://user-images.githubusercontent.com/22958783/34326119-8c2e9cfa-e8e0-11e7-80e4-d358de73339f.PNG)

**Comment by imfanhua** [comment]
下载一半没了是指程序自动消失了还是下载项没了？

**Comment by imfanhua** [comment]
以及temp文件夹下是空的很正常，程序会在开启及关闭时清空temp文件夹里的文件

**Comment by bxz2311196368** [comment]
是下载项消失了

**Comment by imfanhua** [comment]
那肯定是网络问题了，下个版本会改善UI，增加提示
