### ISSUE TITLE
【Bug】下载中出现文件损坏后，无法正常使用

### ISSUE THREAD

**Issue by TartaricAcid** [imfanhua/iCraftDownloader#7]
刚刚在mod百科群的一个名叫`yejue`的用户，在使用`iCraftDowloader`下载`All The Mods`整合包时，出现了无法启动的问题。

![pic](https://public.lightpic.info/image/62F5_5A3F50850.jpg)

但是很奇怪他的mods文件夹下却是有缺失的两个mod。

![pic](https://public.lightpic.info/image/7CA6_5A3F50850.jpg)

我查看了curse上的mod信息后，发现导致这个问题出现的原因是中途网络波动，这两个模组在下载时候损坏了。    
但是由于缓存机制的存在，即使他重复下载，依旧会得到损坏的文件。    
所以我建议下载器能否增加一个MD5校验功能，每次调用缓存时候先进行一次MD5校验。    
curseforge的界面也是提供了文件的MD5值的。

![pic](https://public.lightpic.info/image/D077_5A3F52EC0.jpg)

**Comment by imfanhua** [comment]
可以，下个版本添加

**Comment by imfanhua** [comment]
项目已停止维护
