### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by Aknightofvoid** [imfanhua/iCraftDownloader#9]
![image](https://user-images.githubusercontent.com/29028046/34453230-77ce9ae6-ed89-11e7-8056-9488661ee576.png)
没文件下载了，但是没有到已完成一栏中，什么原因？

**Comment by Aknightofvoid** [comment]
@imfanhua

**Comment by imfanhua** [comment]
与 https://github.com/imfanhua/iCraftDownloader/issues/1 问题相同，解决方案目前还在讨论中（见 https://github.com/imfanhua/iCraftDownloader/issues/5）
